### ISSUE TITLE
What's the 0 property for?

### ISSUE THREAD

**Issue by luokuning** [mstn/fixed-size-array#1]
Hi there, I noticed that there is a `0` property in the `FixedSizeArray` type:

https://github.com/mstn/fixed-size-array/blob/79df3bdcfc0de606c28bdd940736c0fce789e32a/src/index.d.ts#L5

What does that mean? Why should we add this property there? Thanks in advance.

**Comment by mstn** [comment]
Hi, [here](https://mstn.github.io/2018/06/08/fixed-size-arrays-in-typescript/) I explained what is going on. While [here](https://github.com/Microsoft/TypeScript/issues/24680#issuecomment-394616609) there is an explanation for the `0` trick. 

I have not researched this topic further. Maybe you can find more information on the Web today.

**Comment by luokuning** [comment]
Very informative, thanks for sharing! 😄
